from pathlib import Path
import json
number={'type':'number'}
positive={'type':'number','exclusiveMinimum':0}
nonnegative={'type':'number','minimum':0}
string={'type':'string','minLength':1}
id={'type':'string','pattern':'^[a-zA-Z0-9][a-zA-Z0-9._-]*$'}
def obj(properties,required=(),extra=False):return {'type':'object','properties':properties,'required':list(required),'additionalProperties':extra}
def arr(items):return {'type':'array','items':items}
def enum(*values):return {'enum':list(values)}
def ref(name):return {'$ref':'#/definitions/'+name}
definition={}
definition['sourceRef']={'anyOf':[nonnegative,obj({'action':id,'event':enum('start','end','dispatched','verified'),'offsetMs':number},['action'])]}
definition['at']={'oneOf':[obj({'outputMs':nonnegative,'offsetMs':number},['outputMs']),obj({'sourceMs':nonnegative,'offsetMs':number},['sourceMs']),obj({'scene':id,'edge':enum('start','end'),'offsetMs':number},['scene']),obj({'action':id,'event':enum('start','end','dispatched','verified'),'offsetMs':number},['action'])]}
definition['scene']=obj({'id':id,'kind':enum('source','hold','scene'),'fromMs':ref('sourceRef'),'toMs':ref('sourceRef'),'sourceMs':ref('sourceRef'),'rate':{'type':'number','exclusiveMinimum':0,'maximum':16},'durationMs':positive,'duration':obj({'audio':id},['audio']),'entry':string,'adapter':enum('react','module'),'template':enum('background','title','outro','lower','badge','toast','callout'),'props':obj({},extra=True),'assets':{'type':'object','additionalProperties':string},'seed':{'type':'integer'},'camera':ref('camera')},['id','kind'])
definition['layer']=obj({'id':id,'type':enum('title','outro','lower','badge','toast','callout','custom'),'at':ref('at'),'durationMs':positive,'startMs':number,'endMs':number,'timebase':enum('source','output','screenEnd'),'entry':string},['id','type'],True)
definition['audioClip']=obj({'id':id,'file':string,'at':ref('at'),'role':enum('narration','effects','music'),'gainDb':{'type':'number','minimum':-96,'maximum':24},'trimInMs':nonnegative,'trimOutMs':positive,'fadeInMs':nonnegative,'fadeOutMs':nonnegative,'allowOverlap':{'type':'boolean'},'mute':{'type':'boolean'},'captions':obj({'file':string,'text':string})},['id','file','at'])
definition['spring']=obj({k:positive for k in ['stiffness','damping','mass']})
definition['shot']=obj({'id':id,'mode':enum('overview','focus','hold','pull-back'),'at':ref('at'),'durationMs':positive,'target':{'anyOf':[obj({'selector':string},['selector']),obj({'x':number,'y':number,'w':positive,'h':positive},['x','y'])]},'zoom':{'type':'number','minimum':1,'maximum':8}},['id','mode','at','durationMs'])
definition['camera']=obj({'policy':enum('kino','legacy','editorial','off'),'motion':obj({k:ref('spring') for k in ['screen','zoom','mouse']}),'shots':arr(ref('shot')),'kino':obj({'zoom':{'type':'number','minimum':1,'maximum':8},'snapToEdgesRatio':{'type':'number','minimum':0,'exclusiveMaximum':0.5},'alwaysKeepZoomedIn':{'type':'boolean'},'systemZoom':{'type':'number','minimum':1,'maximum':8}})})
definition['cover']={'oneOf':[obj({'type':{'const':'frame'},'atMs':nonnegative},['type','atMs']),obj({'type':{'const':'image'},'file':string,'fit':enum('contain','cover')},['type','file']),obj({'type':{'const':'grid'},'frames':{'type':'array','items':nonnegative,'minItems':1,'maxItems':25},'columns':{'type':'integer','minimum':1,'maximum':25}},['type','frames']),obj({'type':{'const':'scene'},'entry':string,'adapter':enum('react','module'),'template':enum('title','outro','lower','badge','toast','callout'),'props':obj({},extra=True),'assets':{'type':'object','additionalProperties':string},'atMs':nonnegative,'durationMs':positive,'seed':{'type':'integer'}},['type'])]}
properties={'schemaVersion':{'const':2},'capture':string,'output':obj({'width':{'type':'integer','minimum':16,'maximum':7680,'multipleOf':2},'height':{'type':'integer','minimum':16,'maximum':7680,'multipleOf':2},'fps':{'type':'number','minimum':1,'maximum':120}}),'settings':obj({},extra=True),'scenes':{'type':'array','items':ref('scene'),'minItems':1},'layers':arr(ref('layer')),'audioClips':arr(ref('audioClip')),'camera':ref('camera'),'sound':obj({'preset':enum('recorded','subtle','legacy','silent','custom'),'transitions':{'type':'boolean'},'ducking':obj({'enabled':{'type':'boolean'},'gainDb':{'type':'number','minimum':-96,'maximum':0},'attackMs':nonnegative,'releaseMs':nonnegative}),'buses':obj({k:obj({'gainDb':number,'mute':{'type':'boolean'}}) for k in ['narration','effects','music']})}),'captions':obj({'enabled':{'type':'boolean'},'wordHighlight':{'type':'boolean'},'fontSize':positive,'bottomPercent':nonnegative,'color':string,'highlightColor':string}),'cover':ref('cover'),'zoomRanges':arr(obj({},extra=True)),'audioCues':arr(obj({},extra=True)),'screen':obj({},extra=True)}
schema={'$schema':'http://json-schema.org/draft-07/schema#','title':'Cine project v2',**obj(properties,['schemaVersion','capture','scenes']),'definitions':definition}
Path('schemas/project-v2.schema.json').write_text(json.dumps(schema,indent=2)+'\n')
